"""Generate file://-compatible report and documentation from measured data."""

import copy
import html
import json
import re
from pathlib import Path

import markdown

ROOT = Path(__file__).resolve().parent
SCORE_VERSION = "qcec-adjusted-v1"


def build() -> None:
    data = json.loads((ROOT / "data/results.json").read_text())
    display = copy.deepcopy(data)
    display["score_version"] = SCORE_VERSION
    for row in display["results"]:
        for trial in row.get("trials", []):
            trial["validation"].pop("details", None)
    payload = json.dumps(display, ensure_ascii=False).replace("<", "\\u003c")
    template = (ROOT / "web/report.html").read_text()
    if template.count("__BENCHMARK_DATA__") != 1:
        raise ValueError("Expected exactly one data placeholder")
    report = template.replace("__BENCHMARK_DATA__", payload)
    report = report.replace(
        "<!doctype html>", "<!doctype html>\n<!-- Generated by build_site.py; do not edit. -->", 1
    )
    (ROOT / "index.html").write_text(report)
    style = """
    *{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);
    font:14px/1.8 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}
    main{max-width:1040px;margin:auto;padding:35px 30px 70px}a{color:var(--accent);
    text-underline-offset:4px}nav{border-bottom:1px solid var(--border);padding-bottom:20px;
    margin-bottom:35px;display:flex;gap:25px;flex-wrap:wrap;font-size:13px}
    h1{font-size:32px;line-height:1.5;letter-spacing:-.7px}h2{font-size:23px;
    border-top:1px solid var(--border);padding-top:25px;margin-top:45px}h3{font-size:18px}
    .table-scroll{overflow:auto;margin:20px 0}table{border-collapse:collapse;
    font-size:13px;min-width:700px;width:100%;background:var(--bg)}
    th,td{padding:12px;border:1px solid var(--border);text-align:left;vertical-align:top}
    th{background:var(--surface)}code{font:12px/1.8 ui-monospace,monospace;
    background:var(--code-bg);
    padding:2px 5px;overflow-wrap:anywhere}pre{padding:18px;overflow:auto;
    background:var(--pre-bg);color:var(--pre-text);border-radius:6px}
    pre code{background:none;padding:0}
    blockquote{border-left:3px solid #8d77e5;padding-left:20px;color:var(--muted)}
    @media(max-width:600px){main{padding:20px}h1{font-size:26px}}
    """
    for source in sorted((ROOT / "docs").glob("*.md")):
        text = source.read_text()
        text = re.sub(r"\]\(([^)\s]+)\.md(#[^)]*)?\)", r"](\1.html\2)", text)
        body = markdown.markdown(text, extensions=["tables", "fenced_code", "toc"])
        body = body.replace("<table>", '<div class="table-scroll"><table>')
        body = body.replace("</table>", "</table></div>")
        title = html.escape(source.read_text().splitlines()[0].removeprefix("# "))
        page = (
            "<!doctype html>\n<!-- Generated by build_site.py; do not edit. -->\n"
            '<html lang="en"><head><meta charset="utf-8">'
            '<meta name="viewport" content="width=device-width,initial-scale=1">'
            f"<title>{title} | Transpiler Atlas</title>"
            '<script src="../web/theme.js"></script>'
            '<link rel="stylesheet" href="../web/theme.css">'
            f"<style>{style}</style></head>"
            '<body><main><nav aria-label="Documentation navigation">'
            '<a href="../index.html">← Results</a>'
            '<a href="pilot.html">Protocol</a><a href="methodology.html">Scoring</a>'
            '<a href="research.html">Sources</a>'
            '<label class="theme-control" for="theme">Theme<select id="theme">'
            '<option value="light">Light</option><option value="dark">Dark</option>'
            '<option value="system" selected>System</option></select></label>'
            f"</nav>{body}</main></body></html>\n"
        )
        source.with_suffix(".html").write_text(page)
    print("Built index.html and docs/*.html from measured data")


if __name__ == "__main__":
    build()
