"""Read-only integration coverage for the published diagnostic and sealed selector."""

import json

import pytest

import build_site
import publication


def test_diagnostic_uses_verified_seal_and_preserves_root_selector(monkeypatch):
    before = (build_site.ROOT / "publication.json").read_bytes()
    reader = publication.load
    calls = []

    def verified(root, *, file_map):
        calls.append(file_map)
        return reader(root, file_map=file_map)

    monkeypatch.setattr(publication, "load", verified)
    pages = build_site._diagnostic_pages()
    assert len(pages) == len(calls) == 1
    path, page = pages[0]
    assert (
        path.relative_to(build_site.ROOT).as_posix() == "diagnostics/compile-retention/index.html"
    )
    assert page.count("data-identity=") == 18
    assert page.count('class="status">verification_incomplete') == 18
    assert page.count("hard_timeout") == 54
    assert page.count(">Native QPY</a>") == 54
    assert "647 / 99" in page and "666 / 102" in page
    assert "54/54 committed repeats" in page and "0/54 strict accepts" in page
    assert "__ROWS__" not in page
    assert "Generated by build_site.py" in page
    assert "../../docs/retention.html" in page
    build_site._validate_links(pages)
    assert (build_site.ROOT / "publication.json").read_bytes() == before


def test_diagnostic_refuses_unvalidated_seal(monkeypatch):
    def reject(*args, **kwargs):
        raise ValueError("Invalid seal")

    monkeypatch.setattr(publication, "load", reject)
    with pytest.raises(ValueError, match="Invalid seal"):
        build_site._diagnostic_pages()


def test_diagnostic_refuses_wrong_campaign_identity(monkeypatch):
    config = json.loads((build_site.ROOT / "diagnostics/compile-retention/report.json").read_text())
    raw, path = publication.load(build_site.ROOT, file_map=config["file_map"])
    raw["campaign_id"] = "other-campaign"
    monkeypatch.setattr(publication, "load", lambda *args, **kwargs: (raw, path))
    with pytest.raises(ValueError, match="identity mismatch"):
        build_site._diagnostic_pages()
